-- MySQL Script generated by MySQL Workbench
-- Wed Dec  2 20:04:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoSis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProyectoSis` ;

-- -----------------------------------------------------
-- Schema ProyectoSis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoSis` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoSis` ;

-- -----------------------------------------------------
-- Table `ProyectoSis`.`recepcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSis`.`recepcion` (
  `usuario` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoSis`.`dentista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSis`.`dentista` (
  `iddentista` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddentista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoSis`.`consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSis`.`consultorio` (
  `numero` INT NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoSis`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSis`.`paciente` (
  `ci` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `iddentista` INT NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`ci`),
  CONSTRAINT `iddentista`
    FOREIGN KEY (`iddentista`)
    REFERENCES `ProyectoSis`.`dentista` (`iddentista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `ProyectoSis`.`consultorio` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `iddentista_idx` ON `ProyectoSis`.`paciente` (`iddentista` ASC) ;

CREATE INDEX `numero_idx` ON `ProyectoSis`.`paciente` (`numero` ASC) ;


-- -----------------------------------------------------
-- Table `ProyectoSis`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSis`.`cita` (
  `idcita` INT NOT NULL AUTO_INCREMENT,
  `ci` VARCHAR(45) NOT NULL,
  `iddentista2` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcita`),
  CONSTRAINT `ci`
    FOREIGN KEY (`ci`)
    REFERENCES `ProyectoSis`.`paciente` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `iddentista2`
    FOREIGN KEY (`iddentista2`)
    REFERENCES `ProyectoSis`.`dentista` (`iddentista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ci_idx` ON `ProyectoSis`.`cita` (`ci` ASC) ;
CREATE INDEX `iddentista2_idx` ON `ProyectoSis`.`cita` (`iddentista2` ASC) ;


-- -----------------------------------------------------
-- Table `ProyectoSis`.`tratamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSis`.`tratamientos` (
  `idtratamientos` INT NOT NULL AUTO_INCREMENT,
  `tratamiento` VARCHAR(45) NOT NULL,
  `p` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`idtratamientos`),
  CONSTRAINT `p`
    FOREIGN KEY (`p`)
    REFERENCES `ProyectoSis`.`paciente` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `p_idx` ON `ProyectoSis`.`tratamientos` (`p` ASC) ;

-- -----------------------------------------------------
-- Table `ProyectoSis`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSis`.`historial` (
  `idhistorial` INT NOT NULL auto_increment,
  `idpaciente` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `dienteuno` VARCHAR(100) NOT NULL,
  `dientedos` VARCHAR(100) NOT NULL,
  `dientetres` VARCHAR(100) NOT NULL,
  `dientecuatro` VARCHAR(100) NOT NULL,
  `dientecinco` VARCHAR(100) NOT NULL,
  `dienteseis` VARCHAR(100) NOT NULL,
  `dientesiete` VARCHAR(100) NOT NULL,
  `dienteocho` VARCHAR(100) NOT NULL,
  `dientenueve` VARCHAR(100) NOT NULL,
  `dientediez` VARCHAR(100) NOT NULL,
  `dienteonce` VARCHAR(100) NOT NULL,
  `dientedoce` VARCHAR(100) NOT NULL,
  `dientetrece` VARCHAR(100) NOT NULL,
  `dientecato` VARCHAR(100) NOT NULL,
  `dientequnce` VARCHAR(100) NOT NULL,
  `dientedse` VARCHAR(100) NOT NULL,
  `dienteds` VARCHAR(100) NOT NULL,
  `dientedo` VARCHAR(100) NOT NULL,
  `dientedn` VARCHAR(100) NOT NULL,
  `dientev` VARCHAR(100) NOT NULL,
  `dientevu` VARCHAR(100) NOT NULL,
  `dientevd` VARCHAR(100) NOT NULL,
  `dientevt` VARCHAR(100) NOT NULL,
  `dientevcu` VARCHAR(100) NOT NULL,
  `dientevc` VARCHAR(100) NOT NULL,
  `dientevse` VARCHAR(100) NOT NULL,
  `dientevs` VARCHAR(100) NOT NULL,
  `dientevo` VARCHAR(100) NOT NULL,
  `dientevn` VARCHAR(100) NOT NULL,
  `dientet` VARCHAR(100) NOT NULL,
  `dientetu` VARCHAR(100) NOT NULL,
  `dientetd` VARCHAR(100) NOT NULL,
  `precioest` DOUBLE NOT NULL,
  PRIMARY KEY (`idhistorial`),
  CONSTRAINT `idpaciente`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `ProyectoSis`.`paciente` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
 
ENGINE = InnoDB;



CREATE INDEX `idpaciente_idx` ON `ProyectoSis`.`historial` (`idpaciente` ASC) ;

CREATE TABLE IF NOT EXISTS `ProyectoSis`.`montopendiente` (
  `idmontopendiente` INT NOT NULL AUTO_INCREMENT,
  `p2` VARCHAR(45) NOT NULL,
  `montotal` DOUBLE NOT NULL,
   `tratamientohecho` INT NOT NULL,
  PRIMARY KEY (`idmontopendiente`),
  CONSTRAINT `p2`
    FOREIGN KEY (`p2`)
    REFERENCES `ProyectoSis`.`paciente` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `p2_idx` ON `ProyectoSis`.`montopendiente` (`p2` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
